# Generated by Django 4.0 on 2022-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sentimentcheck_social_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentcheck',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
    ]
