# Generated by Django 4.0 on 2022-02-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sentimentcheck_messages_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentcheck',
            old_name='social_network',
            new_name='source',
        ),
    ]
